//
// OSMResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct OSMResponse: Codable {

    public var version: String?
    public var copyright: String?
    public var attribution: String?

    public init(version: String?, copyright: String?, attribution: String?) {
        self.version = version
        self.copyright = copyright
        self.attribution = attribution
    }


}

