//
// UserDetailsResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UserDetailsResponse: Codable {

    public var version: String?
    public var copyright: String?
    public var attribution: String?
    public var user: User?

    public init(version: String?, copyright: String?, attribution: String?, user: User?) {
        self.version = version
        self.copyright = copyright
        self.attribution = attribution
        self.user = user
    }


}

