//
// UserChangesets.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UserChangesets: Codable {

    public var count: Int?

    public init(count: Int?) {
        self.count = count
    }


}

