//
// User.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct User: Codable {

    public var _id: Int?
    public var displayName: String?
    public var accountCreated: Date?
    public var _description: String?
    public var changesets: UserChangesets?
    public var traces: UserTraces?
    public var messages: UserMessages?

    public init(_id: Int?, displayName: String?, accountCreated: Date?, _description: String?, changesets: UserChangesets?, traces: UserTraces?, messages: UserMessages?) {
        self._id = _id
        self.displayName = displayName
        self.accountCreated = accountCreated
        self._description = _description
        self.changesets = changesets
        self.traces = traces
        self.messages = messages
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case displayName = "display_name"
        case accountCreated = "account_created"
        case _description = "description"
        case changesets
        case traces
        case messages
    }

}

