//
// APICapabilitiesChangesets.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct APICapabilitiesChangesets: Codable, Hashable {

    /** The maximum number of combined nodes, ways and relations that can be contained in a changeset */
    public var maximumElements: Double?

    public init(maximumElements: Double? = nil) {
        self.maximumElements = maximumElements
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case maximumElements = "maximum_elements"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(maximumElements, forKey: .maximumElements)
    }
}

