//
// APICapabilitiesArea.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct APICapabilitiesArea: Codable, Hashable {

    /** The maximum area in square degrees that can be queried by API calls */
    public var maximum: Double?

    public init(maximum: Double? = nil) {
        self.maximum = maximum
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case maximum
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(maximum, forKey: .maximum)
    }
}

