//
// APICapabilitiesTracepoints.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct APICapabilitiesTracepoints: Codable, Hashable {

    /** The maximum number of points in a single GPS trace. (Possibly incorrect) */
    public var perPage: Double?

    public init(perPage: Double? = nil) {
        self.perPage = perPage
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case perPage = "per_page"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(perPage, forKey: .perPage)
    }
}

