//
// APICapabilitiesTimeout.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct APICapabilitiesTimeout: Codable, Hashable {

    public var seconds: Double?

    public init(seconds: Double? = nil) {
        self.seconds = seconds
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case seconds
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(seconds, forKey: .seconds)
    }
}

