//
// APICapabilitiesStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The status of the database, API and GPX API. The database field is informational, and the API/GPX-API fields indicate what the client should expect. */
public struct APICapabilitiesStatus: Codable, Hashable {

    public var database: APIStatus?
    public var api: APIStatus?
    public var gpx: APIStatus?

    public init(database: APIStatus? = nil, api: APIStatus? = nil, gpx: APIStatus? = nil) {
        self.database = database
        self.api = api
        self.gpx = gpx
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case database
        case api
        case gpx
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(database, forKey: .database)
        try container.encodeIfPresent(api, forKey: .api)
        try container.encodeIfPresent(gpx, forKey: .gpx)
    }
}

