//
// APIStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Status:   * &#x60;online&#x60; - Both read and write requests work   * &#x60;readonly&#x60; - Only read requests work   * &#x60;offline&#x60; - No requests work  */
public enum APIStatus: String, Codable, CaseIterable {
    case online = "online"
}
