//
// APIVersionsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct APIVersionsResponse: Codable, Hashable {

    public var api: AnyCodable?
    public var version: String
    public var copyright: String
    public var attribution: String

    public init(api: AnyCodable? = nil, version: String, copyright: String, attribution: String) {
        self.api = api
        self.version = version
        self.copyright = copyright
        self.attribution = attribution
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case api
        case version
        case copyright
        case attribution
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(api, forKey: .api)
        try container.encode(version, forKey: .version)
        try container.encode(copyright, forKey: .copyright)
        try container.encode(attribution, forKey: .attribution)
    }
}

