//
// MapElementType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum MapElementType: String, Codable, CaseIterable {
    case node = "node"
    case way = "way"
    case relation = "relation"
}
