//
// Node.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Node: Codable, Hashable {

    public var type: MapElementType?
    public var id: Double?
    public var timestamp: Date?
    public var version: Double?
    public var changeset: Double?
    public var user: String?
    public var uid: Double?
    public var tags: [String: String]?
    public var lat: Double?
    public var lon: Double?

    public init(type: MapElementType? = nil, id: Double? = nil, timestamp: Date? = nil, version: Double? = nil, changeset: Double? = nil, user: String? = nil, uid: Double? = nil, tags: [String: String]? = nil, lat: Double? = nil, lon: Double? = nil) {
        self.type = type
        self.id = id
        self.timestamp = timestamp
        self.version = version
        self.changeset = changeset
        self.user = user
        self.uid = uid
        self.tags = tags
        self.lat = lat
        self.lon = lon
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case id
        case timestamp
        case version
        case changeset
        case user
        case uid
        case tags
        case lat
        case lon
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(timestamp, forKey: .timestamp)
        try container.encodeIfPresent(version, forKey: .version)
        try container.encodeIfPresent(changeset, forKey: .changeset)
        try container.encodeIfPresent(user, forKey: .user)
        try container.encodeIfPresent(uid, forKey: .uid)
        try container.encodeIfPresent(tags, forKey: .tags)
        try container.encodeIfPresent(lat, forKey: .lat)
        try container.encodeIfPresent(lon, forKey: .lon)
    }
}

