//
// OSMResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct OSMResponse: Codable, Hashable {

    public var version: String?
    public var copyright: String?
    public var attribution: String?

    public init(version: String? = nil, copyright: String? = nil, attribution: String? = nil) {
        self.version = version
        self.copyright = copyright
        self.attribution = attribution
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case version
        case copyright
        case attribution
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(version, forKey: .version)
        try container.encodeIfPresent(copyright, forKey: .copyright)
        try container.encodeIfPresent(attribution, forKey: .attribution)
    }
}

