//
// RelationMember.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RelationMember: Codable, Hashable {

    public var type: MapElementType?
    public var ref: Double?
    public var role: String?

    public init(type: MapElementType? = nil, ref: Double? = nil, role: String? = nil) {
        self.type = type
        self.ref = ref
        self.role = role
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case ref
        case role
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encodeIfPresent(ref, forKey: .ref)
        try container.encodeIfPresent(role, forKey: .role)
    }
}

