//
// RelationAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RelationAllOf: Codable, Hashable {

    public var members: [RelationMember]?

    public init(members: [RelationMember]? = nil) {
        self.members = members
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case members
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(members, forKey: .members)
    }
}

