//
// User.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct User: Codable, Hashable {

    public var id: Int?
    public var displayName: String?
    public var accountCreated: Date?
    public var description: String?
    public var changesets: UserChangesets?
    public var traces: UserTraces?
    public var messages: UserMessages?

    public init(id: Int? = nil, displayName: String? = nil, accountCreated: Date? = nil, description: String? = nil, changesets: UserChangesets? = nil, traces: UserTraces? = nil, messages: UserMessages? = nil) {
        self.id = id
        self.displayName = displayName
        self.accountCreated = accountCreated
        self.description = description
        self.changesets = changesets
        self.traces = traces
        self.messages = messages
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case displayName = "display_name"
        case accountCreated = "account_created"
        case description
        case changesets
        case traces
        case messages
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(displayName, forKey: .displayName)
        try container.encodeIfPresent(accountCreated, forKey: .accountCreated)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(changesets, forKey: .changesets)
        try container.encodeIfPresent(traces, forKey: .traces)
        try container.encodeIfPresent(messages, forKey: .messages)
    }
}

