//
// UserMessagesReceived.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UserMessagesReceived: Codable, Hashable {

    public var count: Int?
    public var unread: Int?

    public init(count: Int? = nil, unread: Int? = nil) {
        self.count = count
        self.unread = unread
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case count
        case unread
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(count, forKey: .count)
        try container.encodeIfPresent(unread, forKey: .unread)
    }
}

