//
// UserDetailsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UserDetailsResponse: Codable, Hashable {

    public var user: User?
    public var version: String?
    public var copyright: String?
    public var attribution: String?

    public init(user: User? = nil, version: String? = nil, copyright: String? = nil, attribution: String? = nil) {
        self.user = user
        self.version = version
        self.copyright = copyright
        self.attribution = attribution
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case user
        case version
        case copyright
        case attribution
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(user, forKey: .user)
        try container.encodeIfPresent(version, forKey: .version)
        try container.encodeIfPresent(copyright, forKey: .copyright)
        try container.encodeIfPresent(attribution, forKey: .attribution)
    }
}

