//
// UserMessages.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UserMessages: Codable, Hashable {

    public var received: UserMessagesReceived?
    public var sent: UserMessagesSent?

    public init(received: UserMessagesReceived? = nil, sent: UserMessagesSent? = nil) {
        self.received = received
        self.sent = sent
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case received
        case sent
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(received, forKey: .received)
        try container.encodeIfPresent(sent, forKey: .sent)
    }
}

