//
// WayAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct WayAllOf: Codable, Hashable {

    public var nodes: [Double]

    public init(nodes: [Double]) {
        self.nodes = nodes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case nodes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(nodes, forKey: .nodes)
    }
}

