//
// MapAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class MapAPI {

    /**
     Retrieves map data by the given bounding box.
     
     - parameter bbox: (query) The comma-separated bounding box for which to download the data.  &#x60;left&#x60;,&#x60;bottom&#x60;,&#x60;right&#x60;,&#x60;top&#x60;, where: - &#x60;left&#x60; is the longitude of the left (westernmost) side of the bounding box. - &#x60;bottom&#x60; is the latitude of the bottom (southernmost) side of the bounding box. - &#x60;right&#x60; is the longitude of the right (easternmost) side of the bounding box. - &#x60;top&#x60; is the latitude of the top (northernmost) side of the bounding box.  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the result
     */
    open class func getMapDataByBoundingBox(bbox: String? = nil, apiResponseQueue: DispatchQueue = OpenStreetMap.apiResponseQueue, completion: @escaping ((_ result: Swift.Result<MapDataResponse, Error>) -> Void)) {
        getMapDataByBoundingBoxWithRequestBuilder(bbox: bbox).execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                completion(.success(response.body!))
            case let .failure(error):
                completion(.failure(error))
            }
        }
    }

    /**
     Retrieves map data by the given bounding box.
     - GET /api/0.6/map
     - The operation returns: - All nodes that are inside a given bounding box and any relations that reference them. - All ways that reference at least one node that is inside a given bounding box, any relations that reference them [the ways],   and any nodes outside the bounding box that the ways may reference.  - All relations that reference one of the nodes, ways or relations included due to the above rules.   (Does not apply recursively, see explanation below.)   Note that, while this operation returns those relations that reference the aforementioned nodes and ways, the reverse is not true: it does not (necessarily) return all of the nodes and ways that are referenced by these relations. This prevents unreasonably-large result sets. For example, imagine the case where: - There is a relation named \"England\" that references every node in England. - The nodes, ways, and relations are retrieved for a bounding box that covers a small portion of England.  While the result would include the nodes, ways, and relations as specified by the rules for the command,  including the \"England\" relation, it would (fortuitously) not include every node and way in England.  If desired, the nodes and ways referenced by the \"England\" relation could be retrieved by their respective IDs.  Also note that ways which intersect the bounding box but have no nodes within the bounding box will not be returned.  
     - parameter bbox: (query) The comma-separated bounding box for which to download the data.  &#x60;left&#x60;,&#x60;bottom&#x60;,&#x60;right&#x60;,&#x60;top&#x60;, where: - &#x60;left&#x60; is the longitude of the left (westernmost) side of the bounding box. - &#x60;bottom&#x60; is the latitude of the bottom (southernmost) side of the bounding box. - &#x60;right&#x60; is the longitude of the right (easternmost) side of the bounding box. - &#x60;top&#x60; is the latitude of the top (northernmost) side of the bounding box.  (optional)
     - returns: RequestBuilder<MapDataResponse> 
     */
    open class func getMapDataByBoundingBoxWithRequestBuilder(bbox: String? = nil) -> RequestBuilder<MapDataResponse> {
        let localVariablePath = "/api/0.6/map"
        let localVariableURLString = OpenStreetMap.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "bbox": bbox?.encodeToJSON(),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MapDataResponse>.Type = OpenStreetMap.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }
}
