//
// UserAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class UserAPI {

    /**
     Get the user's profile as well as their OSM messages and preferences
     
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getSignedInUserDetails(apiResponseQueue: DispatchQueue = OpenStreetMap.apiResponseQueue, completion: @escaping ((_ data: UserDetailsResponse?, _ error: Error?) -> Void)) {
        getSignedInUserDetailsWithRequestBuilder().execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Get the user's profile as well as their OSM messages and preferences
     - GET /api/0.6/user/details.json
     - The messages section has been available since mid-2013.
     - BASIC:
       - type: http
       - name: basicAuth
     - returns: RequestBuilder<UserDetailsResponse> 
     */
    open class func getSignedInUserDetailsWithRequestBuilder() -> RequestBuilder<UserDetailsResponse> {
        let localVariablePath = "/api/0.6/user/details.json"
        let localVariableURLString = OpenStreetMap.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<UserDetailsResponse>.Type = OpenStreetMap.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters)
    }
}
